### ISSUE TITLE
snaps for other JetBrains IDEs

### ISSUE THREAD

**Issue by mnagel** [snapcrafters/pycharm-community#6]
Hey there, thank you very much for creating the PyCharm snap.
Are there any plans to create snaps for other JetBrains IDEs (IntelliJ IDEA for example)?
Is this the place to discuss that?

**Comment by evandandrea** [comment]
A snap of IntelliJ IDEA would be a really useful addition. Is that something you'd be willing to get started, @mnagel?

**Comment by mnagel** [comment]
I don't see myself as the person to get this started and/or maintain it on the long run.
I would definitely be willing to do some testing, though.

Best Regards
Michael

**Comment by popey** [comment]
I'm closing this bug as it's not technically an issue with pycharm. I'd also love to see IntelliJ IDEA though :)
