### ISSUE TITLE
snap install pycharm-community returns no snap found

### ISSUE THREAD

**Issue by gsilvapt** [snapcrafters/pycharm-community#8]
As the title suggests, when trying to install snap, console returns there are no snaps with given name. `snap find pycharm` or `snap find pycharm-community` also returns 0 snaps.

Tried the `--edge` flag but with no luck.

**Comment by ARostovsky** [comment]
This should work now, please check.

**Comment by popey** [comment]
```alan@hal:~$ snap find pycharm
Name                  Version   Developer  Notes    Summary
pycharm-community     2017.2.3  jetbrains  classic  Python IDE for Professional Developers
pycharm-professional  2017.2.3  jetbrains  classic  Python IDE for Professional Developers
```

Looks good! Thanks @ARostovsky

**Comment by gsilvapt** [comment]
Thank you!
